#!/bin/bash

REMOTE=$(git config remote.origin.url)

# Removes .git
REMOTE=${REMOTE/.git/}
# Removes http?s://
REMOTE=${REMOTE/http[s]:\/\//}
# Removes @ and change : to /
REMOTE=$(echo $REMOTE | cut -f2 -d@ | tr : /)

echo "https://$REMOTE"
