#!/bin/bash

URL=""

for i in "$@"
do
  case $i in
    -o=*|--open=*)
      MR_ID="${i#*=}"
      shift
    ;;
    -o|--open)
      shift
      MR_ID=$1
    ;;
    -t=*|--target=*)
      OPT_TARGET="${i#*=}"
      shift
    ;;
    -t|--target)
      shift
      OPT_TARGET=$1
    ;;
    --master|-m|master)
      OPT_TARGET=master
      shift
    ;;
    list)
      MR_ID=""
      shift
    ;;
    *)
      MR_ID=$1
      shift
    ;;
  esac
done

get_mr_id_url () {
  echo "Open merge request $1"

  URL="$(git url)/merge_requests/$1"
}

get_new_mr_url () {
  REPO_URL=$(git url)
  SOURCE=$(git branchname)
  PARENT=$(git parent)
  TARGET=${OPT_TARGET:-$PARENT}

  TITLE=$SOURCE

  REGEX_BRANCHNAME="\/?(.*)\_([a-zA-Z]+\-[0-9]+)\-(.*)"

  if [[ $SOURCE =~ $REGEX_BRANCHNAME ]]
  then
    NAME=$(echo "${BASH_REMATCH[1]}:%20${BASH_REMATCH[3]}" | sed -e 's/-/%20/g')
    TITLE="%5B${BASH_REMATCH[2]}%5D%20${NAME}"
  fi

  if [[ $REPO_URL == *"gitlab"* ]]; then
    URL="$REPO_URL/merge_requests/new?merge_request%5Bsource_branch%5D=$SOURCE&merge_request%5Btarget_branch%5D=$TARGET&merge_request%5Btitle%5D=$TITLE"
  elif [[ $REPO_URL == *"github"* ]]; then
    URL="$REPO_URL/compare/$TARGET...$SOURCE?expand=1"
  else
    echo "Not support merge request to this remote"
    exit 1
  fi

  echo "Create Merge Request $SOURCE to $TARGET"
}

if [[ -n ${MR_ID+x} ]]
then
  get_mr_id_url $MR_ID
else
  get_new_mr_url
fi

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  xdg-open $URL
elif [[ "$OSTYPE" == "darwin"* ]]; then
  open $URL
elif [[ "$OSTYPE" == "cygwin" ]]; then
  cygstart $URL
elif [[ "$OSTYPE" == "msys" ]]; then
  start $URL
elif [[ "$OSTYPE" == "win32" ]]; then
  start $URL
else
  echo "Cannot recognize your OS"
  exit 1
fi
